### PR TITLE
Color clean up

### PR DESCRIPTION
**Pull request by kyledold**
Refactored code so that we use readable colors instead of raw hex values.
Apologies for the big PR but sadly this problem touched a lot of files.

### CODE REVIEW

**Review by adrianosbr — APPROVED** [review]
Thanks so much for the PR! Sorry for the late approval, I've been out of time lately.

**Comment by kyledold** [comment]
No worries at all :) 
Sorry for the massive amount of files changed! 
I promise future PRs won't be this big

**Comment by kyledold** [comment]
Hey @adrianosbr i think you may have forgotten to press the merge button?

**Comment by adrianosbr** [comment]
Yeah, I had forgotten 🤦🏻‍♂️

**Pull request merged**
